import { createSlice } from "@reduxjs/toolkit";

// Define the initial state for the shop slice, including categories, products, checked items, radio selections, and brand checkboxes.
const initialState = {
  categories: [], // Array to store categories
  products: [], // Array to store products
  checked: [], // Array to store checked items
  radio: [], // Array to store radio selections
  brandCheckboxes: {}, // Object to store brand checkboxes
  checkedBrands: [], // Array to store checked brands
};

// Create the shop slice using createSlice from Redux Toolkit.
const shopSlice = createSlice({
  name: "shop", // Name of the slice
  initialState, // Initial state
  reducers: {
    // Reducer function to set categories.
    setCategories: (state, action) => {
      state.categories = action.payload; // Update categories in state
    },
    // Reducer function to set products.
    setProducts: (state, action) => {
      state.products = action.payload; // Update products in state
    },
    // Reducer function to set checked items.
    setChecked: (state, action) => {
      state.checked = action.payload; // Update checked items in state
    },
    // Reducer function to set radio selections.
    setRadio: (state, action) => {
      state.radio = action.payload; // Update radio selections in state
    },
    // Reducer function to set selected brand.
    setSelectedBrand: (state, action) => {
      state.selectedBrand = action.payload; // Update selected brand in state
    },
  },
});

// Export actions generated by the shop slice.
export const {
  setCategories,
  setProducts,
  setChecked,
  setRadio,
  setSelectedBrand,
} = shopSlice.actions;

// Export the reducer function generated by the shop slice.
export default shopSlice.reducer;
