import { createSlice } from "@reduxjs/toolkit";

// Create a slice for managing favorite products
const favoriteSlice = createSlice({
  name: "favorites", // Name of the slice
  initialState: [], // Initial state: an empty array
  reducers: {
    // Reducer function to add a product to favorites
    addToFavorites: (state, action) => {
      // Check if the product is not already in favorites
      if (!state.some((product) => product._id === action.payload._id)) {
        state.push(action.payload); // Add the product to favorites
      }
    },
    // Reducer function to remove a product from favorites
    removeFromFavorites: (state, action) => {
      // Remove the product with the matching ID from favorites
      return state.filter((product) => product._id !== action.payload._id);
    },
    // Reducer function to set favorites from localStorage
    setFavorites: (state, action) => {
      // Set the favorites to the payload received
      return action.payload;
    },
  },
});

// Export actions generated by the favoriteSlice
export const { addToFavorites, removeFromFavorites, setFavorites } =
  favoriteSlice.actions;

// Selector function to retrieve favorite products from the state
export const selectFavoriteProduct = (state) => state.favorites;

// Export the reducer function generated by the favoriteSlice
export default favoriteSlice.reducer;
